#pragma once

#ifdef GLOBALCONFIG_EXPORTS
#define GLOBALCONFIG_DECL BOOST_EXTENSION_EXPORT_DECL
#else
#define GLOBALCONFIG_DECL BOOST_EXTENSION_IMPORT_DECL
#endif

#ifdef RECORDER_EXPORTS
#define RECORDER_DECL BOOST_EXTENSION_EXPORT_DECL
#else
#define RECORDER_DECL BOOST_EXTENSION_IMPORT_DECL
#endif